name: mend_ai
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  provider: ^6.1.2

  speech_to_text: ^7.2.0
  flutter_tts: ^4.0.2
  record: ^5.0.4
  audioplayers: ^6.5.0

  audio_waveforms: ^1.0.5

  permission_handler: ^11.4.0

  share_plus: ^7.2.2

  shared_preferences: ^2.2.2

  http: ^1.2.1

  fl_chart: ^0.68.0

  lottie: ^3.3.1

  confetti: ^0.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0

  flutter_screenutil: ^5.9.0

  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11

  google_sign_in: ^7.1.1

  zego_express_engine: ^3.18.0

  flutter_svg: ^2.0.9
  url_launcher: ^6.3.2
  uuid: ^4.4.2
  
  flutter_dotenv: ^5.1.0
  

  flutter_riverpod: ^2.3.6
  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

dependency_overrides:
  record_linux: ^1.1.1


flutter:
  uses-material-design: true
  # Assets
  assets:
    - .env
    - assets/google_logo.svg
    - assets/logo.png
    - assets/lottie/glowing_heart.json
    - assets/lottie/ai_orb.json


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
